# Generated by Django 3.2.10 on 2021-12-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xValue', models.CharField(max_length=200)),
                ('pOfX', models.CharField(max_length=200)),
                ('xPofX', models.CharField(max_length=200)),
                ('xRaiseTwo', models.CharField(max_length=200)),
                ('xRaiseTwoPofX', models.CharField(max_length=200)),
            ],
        ),
    ]
